name: jli_frontend
description: "A new Flutter project."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.2.4 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/card-image-1.png
    - assets/card-image-2.png
    - assets/card-image-3.png
    - assets/card-image-4.png
    - assets/card-image-5.png
    - assets/card-image-6.png
  uses-material-design: true
